#!/bin/sh

# exit with an error if any of the build steps fail
set -e

# Build and install my xmonad and xmobar
stack install

# Copy the xmonad binary to the location xmonad expects to find it
cp -f $(stack path --local-bin)/xmonad $1
